import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "PemmerWebDev Practice Project01",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hu">
      <body className="bg-mainblack text-maingray">{children}</body>
    </html>
  );
}
