import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";

export const metadata: Metadata = {
  title: "PwD personal portfolio practice page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hu">
      <Head>
        <link rel="icon" href="/favicon.png" />
      </Head>
      <body className="bg-mainblack text-maingray">{children}</body>
    </html>
  );
}
